version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - monitor_network

  app1:
    build: .
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
    volumes:
      - .:/app
    networks:
      - monitor_network

  app2:
    build: .
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
    volumes:
      - .:/app
    networks:
      - monitor_network

networks:
  monitor_network:
    driver: bridge 